apiVersion: v1
kind: PersistentVolume
metadata:
  name: nc-nfs-pv
  namespace: nextcloud
spec:
  volumeMode: Filesystem
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.0.230
    path: "/nckube"
