apiVersion: v1
kind: PersistentVolume
metadata:
  name: nc-srv-pv
  namespace: nextcloud
spec:
  volumeMode: Filesystem
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.0.230
    path: "/nc-srv"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nc-srv-pvc
  namespace: nextcloud
  labels:
    app: nextcloud
spec:
  storageClassName: manual
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  namespace: nextcloud
  labels:
    app: nextcloud 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud 
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      volumes:
      - name: nextcloud-storage
        persistentVolumeClaim: 
          claimName: nc-srv-pvc
      containers:
        - image: nextcloud
          name: nextcloud 
          ports:
            - containerPort: 80
          env:
            - name: REDIS_HOST
              value: redis
            - name: MYSQL_HOST
              value: mariadb 
            - name: MYSQL_DATABASE
              value: nextcloud
            - name: MYSQL_PASSWORD
              value: Chaves.2011
            - name: MYSQL_USER
              value: nextcloud
#           - name: NEXTCLOUD_ADMIN_PASSWORD
#             value: Chaves.2011
#           - name: NEXTCLOUD_ADMIN_USER
#             value: "admin"
            - name: NEXTCLOUD_TRUSTED_DOMAINS 
              value: 10.22.1.7 10.22.1.8
          volumeMounts:
            - name: nextcloud-storage
              mountPath: /var/www/html
              subPath: server-data
---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud
  namespace: nextcloud
  labels:
    app: nextcloud
spec:
  type: LoadBalancer
  selector:
    app: nextcloud
  ports:
  - protocol: TCP  
    port: 80
    targetPort: 80
